---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  this template does ......

Metadata:
  template metadata

Parameters:
  set of parameters - a way that a template can ask the import from a user.

Mappings:
  set of mappings

Conditions:
  set of conditions

Transform:
  set of transforms

Resources:
  set of resources

Outputs:
  set of outputs
